version: '3'

services:
  web:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - /home/neon/logistic-backend/.env
    volumes:
      - .:/Helo_logistics
    ports:
      - "9001:8000"
