ECOMMERCE_OWNER = 'ECommerce Owner'
LOGISTIC_EXECUTIVE = 'Logistic Executive'
CUSTOMER = 'Customer'

GENERATED_BY = [
    (ECOMMERCE_OWNER, ECOMMERCE_OWNER),
    (LOGISTIC_EXECUTIVE, LOGISTIC_EXECUTIVE),
    (CUSTOMER, CUSTOMER),
]