ACTIVE = 'Active'
DELIVERED = 'Delivered'
RETURN = 'Return'
CANCELLED = 'Cancelled'
UNFULFILLED = 'Unfulfilled'

ORDER_STATUS = (
    (ACTIVE, ACTIVE),
    (DELIVERED, DELIVERED),
    (RETURN, RETURN),
    (CANCELLED, CANCELLED),
    (UNFULFILLED, UNFULFILLED),
)
HIGH = 1
MEDIUM = 2
LOW = 3

PRIORITY = (
    (HIGH, HIGH),
    (MEDIUM, MEDIUM),
    (LOW, LOW)
)

NO_PACKING = 'No Packing'
LIGHT = 'Light'
SOFT = 'Soft'
HEAVY = 'Heavy'

PACKING_INSTRUCTING = (
    (NO_PACKING, NO_PACKING),
    (LIGHT, LIGHT),
    (SOFT, SOFT),
    (HEAVY, HEAVY),
)

OUTSIDE = 'Outside'
INSIDE = 'Inside'

DELIVERED_LOCATION = (
    (OUTSIDE, OUTSIDE),
    (INSIDE, INSIDE),
)
ONLINE_PAYMENT = 'Online Payment'
CASH_ON_DELIVERY = 'Cash On Delivery'

PAYMENT_CHOICES = (
    (ONLINE_PAYMENT, ONLINE_PAYMENT),
    (CASH_ON_DELIVERY, CASH_ON_DELIVERY)
)

PICK_UP = 'Pick Up'
DELIVERY = 'Delivery'

BUNDLE_CATEGORY = (
    (PICK_UP, PICK_UP),
    (DELIVERY, DELIVERY)
)

PROCESSING = "Processing"
PICK_UP_LIST_GENERATION = "Pick Up List Generation"
STORE_KEEPER_ASSIGNED = "Store Keeper Assigned"
DRIVER_ASSIGNED = "Driver Assigned"
DRIVER_OUT = "Driver Out"
DELIVERED = "Delivered"
BUNDLE_STATUS = (
    (PICK_UP_LIST_GENERATION, PICK_UP_LIST_GENERATION),
    (STORE_KEEPER_ASSIGNED, STORE_KEEPER_ASSIGNED),
    (DRIVER_ASSIGNED, DRIVER_ASSIGNED),
    (PROCESSING, PROCESSING),
    (DELIVERED, DELIVERED),
)
